# This is a basic workflow to help you get started with Actions

name: Create Theme package

# Controls when the workflow will run
on:
 release:
   types:
     - created
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: Titanium-Plates-Theme

      # Runs a single command using the runners shell
      - name: Create ZIP Package
        run: |
          shopt -s dotglob
          zip -r Titanium-Plates-Theme.zip * -x "**/.*" "**/.*/**"

      # Runs a set of commands using the runners shell
      - name: Upload ZIP as release asset
        uses: softprops/action-gh-release@v1
        with:
          files: Titanium-Plates-Theme.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
